Numpy 
===
 

In [1]:
import numpy as np


### 基本属性操作

In [10]:
list = [1,2,3,4,5]
array = np.array(list)
array

array([1, 2, 3, 4, 5])

In [11]:
array.dtype #查看类型

dtype('int32')

In [12]:
array.itemsize  #查看一个该类型所占字节数

4

In [13]:
array.shape

(5,)

In [16]:
array.size  #元素的个数，不关心维度
#或用np.size(array)

5

In [19]:
array.ndim  #显示维度

1

In [22]:
array.fill(0)  #所有值赋值为0
array

array([0, 0, 0, 0, 0])

### 索引与切片

In [26]:
list = [1,2,3,4,5]
array = np.array(list)
array[0]

1

In [27]:
array[1:3]

array([2, 3])

In [28]:
array[-2:]

array([4, 5])

### 矩阵

In [29]:
array = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
array.shape

(3, 3)

In [31]:
array.size

9

In [32]:
array.ndim

2

In [33]:
array[1,1]

5

In [34]:
array[1,1] = 10 #赋值
array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [35]:
array[1]

array([ 4, 10,  6])

In [37]:
array[:,1] #取列

array([ 2, 10,  8])

In [38]:
array[0,0:2]

array([1, 2])

### 数组拷贝

In [44]:
array2 = array
array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [42]:
array2[1,1] = 100
array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [43]:
array  #不能这么拷贝

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

#### 若要拷贝，需如下操作

In [46]:
array2 = array.copy()
array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [47]:
array2[1,1] = 10000
array2

array([[    1,     2,     3],
       [    4, 10000,     6],
       [    7,     8,     9]])

In [48]:
array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

### 等差

In [49]:
array = np.arange(0,100,10)
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
mask = np.array([0,0,0,1,1,1,0,0,1,1,],dtype=bool)
mask

array([False, False, False,  True,  True,  True, False, False,  True,
        True])

In [54]:
array[mask]   #找对应值

array([30, 40, 50, 80, 90])

### 随机数&布尔索引

In [61]:
#np.random.randint(a, b, size=(c, d))，可指定范围
np.random.randint(1, 10, size=(2,3))

array([[2, 8, 6],
       [3, 9, 3]])

In [57]:
random_array = np.random.rand(10)
random_array

array([0.74431652, 0.61055368, 0.82078419, 0.62267704, 0.98825086,
       0.48299121, 0.21413119, 0.20378514, 0.18961883, 0.03938187])

In [58]:
#可构造布尔类型
mask = random_array > 0.5
mask

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [60]:
random_array[mask]

array([0.74431652, 0.61055368, 0.82078419, 0.62267704, 0.98825086])

In [62]:
array = np.array([10,20,30,40,50])
array > 30

array([False, False, False,  True,  True])

In [63]:
np.where(array > 30)  #返回的3，4是索引

(array([3, 4], dtype=int64),)

In [64]:
array[np.where(array > 30)]

array([40, 50])

### 数组类型

In [66]:
array = np.array([1,2,3,4,5],dtype = np.float32)
array

array([1., 2., 3., 4., 5.], dtype=float32)

In [67]:
array.dtype

dtype('float32')

In [68]:
array.nbytes #一共占用的字节数

20

In [70]:
#若想在一个array下存多类型 则用np.object
array = np.array([1,10,3.5,'str'],dtype = np.object) 
array

array([1, 10, 3.5, 'str'], dtype=object)

In [71]:
array * 2

array([2, 20, 7.0, 'strstr'], dtype=object)

In [72]:
#将原始ndarray类型进行转换，用np.asarray(array,dtype = )
array = np.array([1,2,3,4,5])
np.asarray(array,dtype = np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [74]:
array2 = np.asarray(array,dtype = np.float32)
array2

array([1., 2., 3., 4., 5.], dtype=float32)

In [75]:
#或者也可以用astype
array.astype(np.float32)
#array2 = array.astype(np.float32),用的话需要单独赋值

array([1., 2., 3., 4., 5.], dtype=float32)