# 运算

In [3]:
import numpy as np

### 乘

In [4]:
#对应元素相乘
x = np.array([5,5])
y = np.array([2,2])
np.multiply(x,y)

array([10, 10])

In [5]:
#矩阵乘法
np.dot(x,y) #这里是内积

20

#### 若x和y维度不一样，则会自动补全
但是一般不这么写

In [6]:
x = np.array([1,1,1])
y = np.array([[1,2,3],[4,5,6]])
print (x * y)

[[1 2 3]
 [4 5 6]]


In [7]:
x = np.array([1,1,1])
y = np.array([1,1,1])
x == y  #基本判断操作

array([ True,  True,  True])

In [9]:
x = np.array([1,1,1,4])
y = np.array([1,1,1,2])
x == y

array([ True,  True,  True, False])

#### 逻辑操作

In [10]:
np.logical_and(x,y)  #逻辑与操作

array([ True,  True,  True,  True])

In [11]:
np.logical_or(x,y)  #逻辑或操作

array([ True,  True,  True,  True])

In [12]:
np.logical_not(x,y)  #逻辑非操作

array([0, 0, 0, 0])