# 数组形状操作

In [2]:
import numpy as np
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
array.shape

(10,)

In [4]:
#两种方法，可以直接赋值给.shape或者用reshape()
array.shape = 2,5   
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
array.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### 新增加维度
#### 区别 array[np.newaxis,:] 和 array[:,np.newaxis] ，示例如下
将np.newaxis理解为1

In [10]:
array = np.arange(10)
print(array)
print(array.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [11]:
array = array[np.newaxis,:]
print(array)
print(array.shape)

[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)


In [15]:
array = np.arange(10)
print(array)
print(array.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [16]:
array = array[:,np.newaxis]
print(array)
print(array.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


### 压缩轴
.squeeze()

In [17]:
print(array)
print(array.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


In [18]:
array = array[:,np.newaxis,np.newaxis]
array.shape

(10, 1, 1, 1)

In [19]:
array = array.squeeze()
array.shape

(10,)

### 转置

In [20]:
array.shape = 2,5
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
array.transpose()  #或直接用.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [23]:
array.T  #执行.T或者transpose()后原始的array是不变的

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

### 数组的连接
np.concatenate((a,b))

In [24]:
a = np.array([[123,456,678],[3214,456,134]])
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [25]:
b = np.array([[1235,3124,432],[43,13,134]])
b

array([[1235, 3124,  432],
       [  43,   13,  134]])

In [27]:
c = np.concatenate((a,b))  #传进一个元组的形式，默认是第一个维度进行拼接，axis=0
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [29]:
c = np.concatenate((a,b),axis = 1)
c

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

#### np.vstack & np.hstack

In [30]:
np.vstack((a,b))

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [31]:
np.hstack((a,b))

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

### 拉平
.flatten() 或 .ravel()

In [33]:
# 拉平操作
print(a)
a.flatten()

[[ 123  456  678]
 [3214  456  134]]


array([ 123,  456,  678, 3214,  456,  134])

In [34]:
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [35]:
a.ravel()

array([ 123,  456,  678, 3214,  456,  134])