# 数组生成

In [15]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [16]:
np.arange(10) #相当于构造索引

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(2,20,2) #生成范围为[2,20｝,隔2一跳

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.arange(2,20,2,dtype = np.float32) #也可以指定数据类型

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.], dtype=float32)

#### np.linespace()
与arange的区别是头和尾都包括在生成的array里面

In [19]:
np.linspace(0,10,50) #起始是0，终止是10(包含)，构造50个数(等距)，自动计算平均距离

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [20]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

### 可查看帮助文档

In [21]:
print(help(np.logspace))

Help on function logspace in module numpy.core.function_base:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    Parameters
    ----------
    start : float
        ``base ** start`` is the starting value of the sequence.
    stop : float
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    base : float, optional
        The base of 

In [22]:
np.logspace(0,1,5)  #np.logspace()默认以10为底

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

### 网格

In [23]:
x = np.linspace(-10,10,5)
x

array([-10.,  -5.,   0.,   5.,  10.])

In [24]:
y = np.linspace(-10,10,5)
y

array([-10.,  -5.,   0.,   5.,  10.])

In [25]:
#该命令的结果是产生5*7的矩阵（X,Y都是5*7的矩阵；其中X是由第一个含7个元素的行向量产生，Y是由第二个行向量产生） 2、 meshgrid是MATLAB中用于生
x , y = np.meshgrid(x,y)

In [26]:
x

array([[-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.]])

In [27]:
y

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

In [28]:
#产生行向量
np.r_[0:10,1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1])

In [29]:
#产生列向量
np.c_[0:10:1]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### 更常用的

In [30]:
np.zeros(3)

array([0., 0., 0.])

In [31]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.ones((3,3)) * 8

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [36]:
np.ones((3,3), dtype = np.float32)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [41]:
x = np.empty(6) #构造空的数组结构（实际上里面还是有随机值的）,很少会用到
x.shape

(6,)

In [42]:
x.fill(1)
x

array([1., 1., 1., 1., 1., 1.])

In [43]:
array = np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [44]:
np.zeros_like(array) #复制维度

array([0, 0, 0, 0])

In [45]:
np.ones_like(array) #复制维度

array([1, 1, 1, 1])

In [46]:
np.identity(5) #单位矩阵，只有对角线元素为1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])