# 使用numpy文件读写

In [ ]:
import numpy as np

In [2]:
#用魔法指令写文件
%%writefile test.txt
1 2 3 4 5 6
2 3 5 8 7 9

Writing test.txt


In [3]:
#正常读取上面文件
data = []
with open('test.txt') as f:
    for line in f:
        fileds = line.split() # 按照空格切分
        cur_data = [float(x) for x in fileds]
        data.append(cur_data)
data = np.array(data)
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

### 用np.loadtxt()读文件

In [5]:
data = np.loadtxt('test.txt') #不加参数这样读文件的前提是空格分割
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [6]:
%%writefile test2.txt
1,2,3,4,5,6
2,3,5,8,7,9

Writing test2.txt


In [7]:
data = np.loadtxt('test2.txt',delimiter=',')  #额外指定参数delimiter
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

In [9]:
%%writefile test3.txt
x,y,z,w,a,b  #给每列指定了名字
1,2,3,4,5,6
2,3,5,8,7,9

Writing test3.txt


In [11]:
data = np.loadtxt('test3.txt',delimiter = ',',skiprows = 1)  #额外指定参数delimiter和去掉第一行 skiprows = 1
data

array([[1., 2., 3., 4., 5., 6.],
       [2., 3., 5., 8., 7., 9.]])

* 'test3.txt':路径最好放到和代码一起
* skiprows : 去掉几行
* delimiter = ',' :分隔符
* usecols = (0,1,4) ：指定使用哪几列

### 用numpy写文件
* np.savetxt()

In [13]:
array = np.array([[1,2,3],[4,5,6]])
np.savetxt('test4.txt',array)

In [14]:
np.savetxt('test5.txt',array,fmt='%d') #fmt=，指定格式，否则会保存成科学计数法格式..

In [15]:
np.savetxt('test6.txt',array,fmt='%d',delimiter = ',') #用，为分隔符保存

In [16]:
np.savetxt('test7.txt',array,fmt='%.2f',delimiter = ',') #用，为分隔符保存,保存为浮点数

### 读写array结构
* np.save()
* np.load()
* np.savez()

In [17]:
array = np.array([[1,2,3],[4,5,6]])
np.save('array.npy',array)  #直接存ndarray结构

In [18]:
#直接读取.npy文件
a = np.load('array.npy')
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
array2 = np.arange(10)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.savez('me.npz',a = array,b = array2) 
#类似存成一个字典的形式的文件，这种npz文件可用压缩工具打开，打开后里面有a.npy和b.npy文件

In [23]:
data = np.load('me.npz')

In [24]:
data.keys()

['b', 'a']

In [25]:
data['a']

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
data['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])