## array数组的数值计算

In [1]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
np.sum(array) #所有的数加在一起求和

21

In [3]:
#按照维度求和
np.sum(array,axis = 0)

array([5, 7, 9])

In [4]:
np.sum(array,axis = 1)

array([ 6, 15])

In [5]:
# -1 即为按维度最高的一个轴
np.sum(array,axis = -1)

array([ 6, 15])

In [6]:
#也可以直接用array来加
array.sum(axis = 0)

array([5, 7, 9])

### 元素的乘积

In [7]:
array.prod() #1*2*3*4*5*6

720

In [8]:
array.prod(axis = 0)

array([ 4, 10, 18])

In [9]:
array.prod(axis = 1)

array([  6, 120])

### 找特殊值

In [10]:
#找最小值
array.min()

1

In [12]:
array.min(axis = 0)

array([1, 2, 3])

In [13]:
#找最小(大)索引
array.argmin()

0

In [14]:
array.argmin(axis = 0)

array([0, 0, 0], dtype=int64)

In [15]:
array.argmin(axis = 1)

array([0, 0], dtype=int64)

In [16]:
array.argmax()

5

In [17]:
array.argmax(axis = 0)

array([1, 1, 1], dtype=int64)

In [18]:
#均值
array.mean()

3.5

In [19]:
array.mean(axis = 0)

array([2.5, 3.5, 4.5])

In [20]:
#标准差
array.std()

1.707825127659933

In [21]:
array.std(axis = 1)

array([0.81649658, 0.81649658])

In [22]:
#方差
array.var()

2.9166666666666665

### 做限制

In [23]:
array.clip(2,4) #array中小于2的值都为2，大于4的值都为4

array([[2, 2, 3],
       [4, 4, 4]])

In [24]:
array = np.array([1.2,3.56,6.41])
array.round() #四舍五入

array([1., 4., 6.])

In [25]:
#四舍五入指定精度
array.round(decimals = 1)

array([1.2, 3.6, 6.4])