# 排序

In [1]:
import numpy as np
array = np.array([[1.5,1.3,7.5],
                [5.6,7.8,1.2]])
array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [2]:
np.sort(array) #默认为最后一个轴排序

array([[1.3, 1.5, 7.5],
       [1.2, 5.6, 7.8]])

In [3]:
np.sort(array,axis = 0)

array([[1.5, 1.3, 1.2],
       [5.6, 7.8, 7.5]])

In [4]:
np.argsort(array) #索引排序

array([[1, 0, 2],
       [2, 0, 1]], dtype=int64)

# 插入

In [5]:
array = np.linspace(0,10,10) #构造一个array
array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [7]:
values = np.array([2.5,6.5,9.5]) #想插入的数

In [8]:
np.searchsorted(array,values) #array必须是一个排序好的数组，才能用searchsorted

array([3, 6, 9], dtype=int64)

# 在规定条件下升降序
### 在第2列为升序的情况下，第一列为降序

写法为np.lexsort([-1*array[:,0],array[:,2]])


In [12]:
array = np.array([[1,0,6],
                [1,7,0],
                [2,3,1],
                [2,4,0]])
array

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

In [15]:
index = np.lexsort([-1*array[:,0],array[:,2]])
index

array([3, 1, 2, 0], dtype=int64)

In [16]:
array[index]

array([[2, 4, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])

## 尽量用pandas的排序