# 随机模块

In [1]:
import numpy as np
#所有的值都是从0到1
np.random.rand(3,2)

array([[0.72906008, 0.29159167],
       [0.23215656, 0.17414708],
       [0.60433847, 0.19040738]])

In [3]:
#从0到10的整数,返回随机整数，左闭右开区间
np.random.randint(10,size = (5,4))

array([[9, 5, 1, 4],
       [8, 4, 7, 1],
       [4, 4, 4, 7],
       [7, 2, 9, 2],
       [7, 9, 7, 0]])

In [4]:
#返回一个数
np.random.rand()

0.6006642682979458

In [5]:
#返回0-1的浮点数另一种方法，用的较少
np.random.random_sample()

0.34913875982206266

In [7]:
# [0,10)之间选3个数
np.random.randint(0,10,3)

array([3, 1, 3])

### 高斯分布
np.random.normal()

In [9]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10) #高斯分布

array([ 0.11669785, -0.18556909, -0.03777763, -0.05037979, -0.00707713,
        0.11131651,  0.02949448, -0.01839568, -0.04273212,  0.06981244])

In [10]:
np.set_printoptions(precision = 3) #设置随机数的精度

In [11]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10) #高斯分布

array([-0.054, -0.048,  0.085, -0.035, -0.004, -0.027,  0.267,  0.167,
        0.048,  0.041])

### 洗牌

In [12]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.random.shuffle(array)
array

array([5, 9, 0, 3, 6, 2, 4, 1, 7, 8])

#### 随机种子

In [16]:
np.random.seed(0)
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10) 

array([ 0.176,  0.04 ,  0.098,  0.224,  0.187, -0.098,  0.095, -0.015,
       -0.01 ,  0.041])