# Numpy实例&示例

In [1]:
import numpy as np
print (np.__version__) #打印版本号

1.14.2


#### 构造一个全零的矩阵，并打印其占用的内存大小

In [2]:
z = np.zeros((5,5))
print ('%d bytes'%(z.size * z.itemsize))

200 bytes


#### 打印一个函数的帮助文档，比如numpy.add

In [3]:
print (help(np.info(np.add)))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 创建一个10-49的数组，并将其倒序排列
* 倒序[::-1]

In [11]:
array = np.arange(10,50,1)
array = array[::-1]
array

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 找到一个数组中不为0的索引

In [12]:
np.nonzero([1,2,3,4,5,0,0,0,1234,0,1])

(array([ 0,  1,  2,  3,  4,  8, 10], dtype=int64),)

#### 随机构造一个3*3矩阵，并打印其中最大与最小值

In [14]:
array = np.random.random((3,3))
print(array)
print(array.min())
print(array.max())

[[0.83613625 0.61839026 0.37278619]
 [0.81224676 0.77780416 0.09930496]
 [0.37132668 0.5604405  0.49836036]]
0.09930495957051177
0.8361362478774759


#### 构造一个5*5的矩阵，令其值都为1，并在最外层加上两圈0
* np.pad()

In [18]:
#也就是边缘填充，多用于图像处理
array = np.ones((5,5))
array = np.pad(array,pad_width = 2,mode = 'constant',constant_values = 0)
array
# print(help(np.pad))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 构建一个shape为（6，7，8）的矩阵，并找到第100个元素的索引值

In [19]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 对一个5*5的矩阵做归一化操作

In [24]:
array = np.random.random((5,5))
array_max = array.max()
array_min = array.min()
array = (array-array_min)/(array_max - array_min)
array

array([[0.97960189, 0.49650434, 0.18060559, 0.48639998, 0.2105228 ],
       [0.93502196, 0.61756565, 0.78486024, 0.01143652, 0.03104828],
       [0.        , 0.640215  , 0.0129001 , 1.        , 0.5339727 ],
       [0.87848738, 0.46283705, 0.55155799, 0.58593504, 0.80931735],
       [0.81759746, 0.1209409 , 0.74393031, 0.35156139, 0.37825818]])

#### 找到两个数组中相同的值
* np.intersect1d(z1,z2)

In [30]:
z1 = np.random.randint(0,10,10) 
z2 = np.random.randint(0,10,10)
print (z1)
print (z2)
print (np.intersect1d(z1,z2))

[1 2 7 1 5 4 4 3 7 0]
[5 0 6 6 7 4 1 1 0 4]
[0 1 4 5 7]


#### 得到今天 明天 昨天的日期
* np.datetime64()
* np.timedelta()

In [31]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')

#### 得到一个月中所有的天

In [46]:
np.arange('2018-02','2018-03',dtype='datetime64[D]')

array(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
       '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08',
       '2018-02-09', '2018-02-10', '2018-02-11', '2018-02-12',
       '2018-02-13', '2018-02-14', '2018-02-15', '2018-02-16',
       '2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20',
       '2018-02-21', '2018-02-22', '2018-02-23', '2018-02-24',
       '2018-02-25', '2018-02-26', '2018-02-27', '2018-02-28'],
      dtype='datetime64[D]')

#### 得到一个数的整数部分

In [50]:
z = np.random.uniform(0,10,10)
print(z)
np.floor(z)

[9.03927358 6.95103055 3.47090911 9.64440595 9.05713314 7.37482392
 9.61345591 6.36632437 2.36303544 1.38282754]


array([9., 6., 3., 9., 9., 7., 9., 6., 2., 1.])

#### 构造一个数组，让它不能被改变

In [51]:
z = np.zeros(5)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

#### 打印大数据的部分值，全部值
* np.set_printoptions()

np.set_printoptions()还可以指定精度np.set_printoptions(precision=4)

In [54]:
np.set_printoptions(threshold=5)
z = np.zeros((15,15))
z

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

#### 找到在一个数组中，最接近一个数的索引

In [55]:
z = np.arange(100)
v = np.random.uniform(0,100)
print (v)
index = (np.abs(z-v)).argmin()
print (z[index])

91.04136234334506
91


#### 32位float类型和32位int类型转换

In [59]:
z = np.arange(10,dtype=np.int32)
print (z.dtype)
z = z.astype(np.float32)
print (z.dtype)

int32
float32


#### 打印数组元素位置坐标与数值
* np.ndenumerate()

In [61]:
z = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(z):
    print (index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 按照数组的某一列进行排序

In [62]:
z = np.random.randint(0,10,(3,3))
print (z)
print (z[z[:,1].argsort()])

[[7 7 5]
 [3 2 0]
 [2 2 7]]
[[3 2 0]
 [2 2 7]
 [7 7 5]]


#### 统计数组中每个数值出现的次数
* np.bincount(z)

z为一个int类型array，此函数统计从0到array中最大值中每个数出现的次数

In [71]:
z = np.array([1,1,1,2,2,3,3,4,5,8])
print(np.bincount(z))
print(np.bincount(z).shape)
#array([0, 3, 2, ..., 0, 0, 1], dtype=int64) 的意思是0出现了0次，1出现了3次，2出现了2次....8出现了1次

[0 3 2 ... 0 0 1]
(9,)


#### 如何对一个四维数组的最后两维来求和

In [72]:
z = np.random.randint(0,10,(4,4,4,4))
res = z.sum(axis=(-2,-1))
res

array([[67, 83, 67, 92],
       [57, 67, 46, 69],
       [71, 80, 76, 63],
       [68, 75, 88, 59]])

#### 交换矩阵中的两行

In [73]:
z = np.arange(25).reshape(5,5)
z[[0,1]] = z[[1,0]]
z

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 找到一个数组中最常出现的数字

In [82]:
z = np.random.randint(0,10,50)
print(z)
print (np.bincount(z).argmax())

[5 3 4 ... 6 4 5]
5


#### 快速查找TOP K
* np.argpartition()

array[np.argpartition(-array,k)[:k]]


In [105]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5
print (z[np.argpartition(-z,n)[:n]]) #-z的原因是argpartition()默认从低到高，因此加负号

[9999 9998 9997 9996 9995]


#### 去除掉一个数组中，所有元素都相同的数据
* all
* any

In [111]:
np.set_printoptions(threshold=np.nan)
z = np.random.randint(0,3,(10,3))
z

array([[0, 2, 1],
       [0, 0, 0],
       [2, 1, 1],
       [1, 2, 1],
       [1, 0, 0],
       [1, 1, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 1, 2],
       [1, 1, 1]])

In [112]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,5])
print(np.all(a == b))
print(np.any(a == b))

False
True


In [120]:
e = np.all(z[:,1:] == z[:,:-1],axis = 1) # axis = 1 表示一行一行判断
print (e)

[False  True False False False False  True False False  True]
